# Generated by Django 4.2.7 on 2023-11-16 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema_Aislado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='Sistema_Aislado/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sistema_Aislado',
                'verbose_name_plural': 'Sistemas_Aislados',
                'db_table': 'Sistema_Aislado',
                'ordering': ['id'],
            },
        ),
    ]
