# Generated by Django 4.2.7 on 2023-11-15 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transmision1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='Transmision/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transmision1',
                'verbose_name_plural': 'Transmisions1',
                'db_table': 'transmision_varios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='Transmision/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transmision',
                'verbose_name_plural': 'Transmisions',
                'db_table': 'transmision',
                'ordering': ['id'],
            },
        ),
    ]
