# Generated by Django 4.2.8 on 2023-12-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transmision', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transmision',
            options={'ordering': ['id'], 'verbose_name': 'DiagramasUnifilares', 'verbose_name_plural': 'Transmisions'},
        ),
        migrations.AlterModelOptions(
            name='transmision1',
            options={'ordering': ['id'], 'verbose_name': 'Varios', 'verbose_name_plural': 'Transmisions1'},
        ),
    ]
