# Generated by Django 4.2.8 on 2023-12-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(default='empty.png', upload_to='perfil/', verbose_name='Imagen del perfil'),
        ),
    ]
