# Generated by Django 4.2.7 on 2023-11-16 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BajaTension99',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH099',
                'db_table': 'BajaTension99',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension98',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH098',
                'db_table': 'BajaTension98',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension97',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH097',
                'db_table': 'BajaTension197',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension96',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH096',
                'db_table': 'BajaTension96',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension95',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH095',
                'db_table': 'BajaTension95',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension94',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH094',
                'db_table': 'BajaTension94',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension93',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH093',
                'db_table': 'BajaTension93',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension92',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH092',
                'db_table': 'BajaTension92',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension91',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH091',
                'db_table': 'BajaTension91',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension90',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH090',
                'db_table': 'BajaTension90',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH009',
                'db_table': 'BajaTension9',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension89',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH089',
                'db_table': 'BajaTension89',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension86',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH086',
                'db_table': 'BajaTension86',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension81',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH081',
                'db_table': 'BajaTension81',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension80',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH080',
                'db_table': 'BajaTension80',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH008',
                'db_table': 'BajaTension8',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension79',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH079',
                'db_table': 'BajaTension79',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension78',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH078',
                'db_table': 'BajaTension78',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension77',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH077',
                'db_table': 'BajaTension77',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension76',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH076',
                'db_table': 'BajaTension76',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension75',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH075',
                'db_table': 'BajaTension75',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension74',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH074',
                'db_table': 'BajaTension74',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension73',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH073',
                'db_table': 'BajaTension73',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension72',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH072',
                'db_table': 'BajaTension72',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension71',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH071',
                'db_table': 'BajaTension71',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension70',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH070',
                'db_table': 'BajaTension70',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH007',
                'db_table': 'BajaTension7',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension69',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH069',
                'db_table': 'BajaTension69',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension68',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH068',
                'db_table': 'BajaTension68',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension67',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH067',
                'db_table': 'BajaTension67',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension66',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH066',
                'db_table': 'BajaTension66',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension65',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH065',
                'db_table': 'BajaTension65',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension64',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH064',
                'db_table': 'BajaTension64',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension63',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH063',
                'db_table': 'BajaTension63',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension62',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH062',
                'db_table': 'BajaTension62',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension61',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH061',
                'db_table': 'BajaTension61',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension60',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH060',
                'db_table': 'BajaTension60',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH006',
                'db_table': 'BajaTension6',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension59',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH059',
                'db_table': 'BajaTension59',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension58',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH058',
                'db_table': 'BajaTension58',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension57',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH057',
                'db_table': 'BajaTension57',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension56',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH056',
                'db_table': 'BajaTension56',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension55',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH055',
                'db_table': 'BajaTension55',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension54',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH054',
                'db_table': 'BajaTension54',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension53',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH053',
                'db_table': 'BajaTension53',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension52',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH052',
                'db_table': 'BajaTension52',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension51',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH051',
                'db_table': 'BajaTension51',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension50',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH050',
                'db_table': 'BajaTension50',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH005',
                'db_table': 'BajaTension5',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension48',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH048',
                'db_table': 'BajaTension48',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension47',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH047',
                'db_table': 'BajaTension47',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension46',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH046',
                'db_table': 'BajaTension46',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension43',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH043',
                'db_table': 'BajaTension43',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension42',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH042',
                'db_table': 'BajaTension42',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension41',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH041',
                'db_table': 'BajaTension41',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension40',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH040',
                'db_table': 'BajaTension40',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH004',
                'db_table': 'BajaTension4',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension39',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH039',
                'db_table': 'BajaTension39',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension38',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH038',
                'db_table': 'BajaTension38',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension37',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH037',
                'db_table': 'BajaTension37',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension36',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH036',
                'db_table': 'BajaTension36',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension34',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH034',
                'db_table': 'BajaTension34',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension33',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH033',
                'db_table': 'BajaTension33',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension32',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH032',
                'db_table': 'BajaTension32',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension31',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH031',
                'db_table': 'BajaTension31',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension30',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH030',
                'db_table': 'BajaTension30',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH003',
                'db_table': 'BajaTension3',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension28',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH028',
                'db_table': 'BajaTension28',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension27',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH027',
                'db_table': 'BajaTension27',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension26',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH026',
                'db_table': 'BajaTension26',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH025',
                'db_table': 'BajaTension25',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH024',
                'db_table': 'BajaTension24',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension23',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH023',
                'db_table': 'BajaTension23',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH022',
                'db_table': 'BajaTension22',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH021',
                'db_table': 'BajaTension21',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH020',
                'db_table': 'BajaTension20',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH002',
                'db_table': 'BajaTension2',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH019',
                'db_table': 'BajaTension19',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH018',
                'db_table': 'BajaTension18',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension17',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH017',
                'db_table': 'BajaTension17',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH016',
                'db_table': 'BajaTension16',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension159',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH159',
                'db_table': 'BajaTension159',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension158',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH158',
                'db_table': 'BajaTension158',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension157',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH157',
                'db_table': 'BajaTension157',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension153',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH153',
                'db_table': 'BajaTension153',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH015',
                'db_table': 'BajaTension15',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension142',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH142',
                'db_table': 'BajaTension142',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH014',
                'db_table': 'BajaTension14',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension131',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH131',
                'db_table': 'BajaTension131',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension130',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH130',
                'db_table': 'BajaTension130',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH013',
                'db_table': 'BajaTension13',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension129',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH129',
                'db_table': 'BajaTension129',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension128',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH128',
                'db_table': 'BajaTension128',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension127',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH127',
                'db_table': 'BajaTension127',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension126',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH126',
                'db_table': 'BajaTension126',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension125',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH125',
                'db_table': 'BajaTension125',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension124',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH124',
                'db_table': 'BajaTension124',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension122',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH122',
                'db_table': 'BajaTension122',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension121',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH121',
                'db_table': 'BajaTension121',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension120',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH120',
                'db_table': 'BajaTension120',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH012',
                'db_table': 'BajaTension12',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension114',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH114',
                'db_table': 'BajaTension114',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension113',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH113',
                'db_table': 'BajaTension113',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension112',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH112',
                'db_table': 'BajaTension112',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension111',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH111',
                'db_table': 'BajaTension111',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension110',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH110',
                'db_table': 'BajaTension110',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH011',
                'db_table': 'BajaTension11',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension109',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH109',
                'db_table': 'BajaTension109',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension107',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH107',
                'db_table': 'BajaTension107',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension106',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH106',
                'db_table': 'BajaTension106',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension102',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH102',
                'db_table': 'BajaTension102',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension101',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH101',
                'db_table': 'BajaTension101',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension100',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH100',
                'db_table': 'BajaTension100',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH010',
                'db_table': 'BajaTension10',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BajaTension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('files', models.FileField(upload_to='BajaTension/%d/%m/%Y')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BajaTension',
                'verbose_name_plural': 'BajaTensions_PCH001',
                'db_table': 'BajaTension',
                'ordering': ['id'],
            },
        ),
    ]
