# Generated by Django 4.2.6 on 2023-10-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estructura',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CODIGO', models.CharField(blank=True, max_length=255, null=True)),
                ('CODIGO_VNR', models.CharField(blank=True, max_length=255, null=True)),
                ('TIPO', models.CharField(blank=True, max_length=255, null=True)),
                ('PROPIEDAD', models.CharField(blank=True, max_length=255, null=True)),
                ('ESTADO', models.CharField(blank=True, max_length=255, null=True)),
                ('LATITUD', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('LONGITUD', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('CLASIFICACI', models.CharField(blank=True, max_length=255, null=True)),
                ('ALTURA', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('OPERATIVO', models.CharField(blank=True, max_length=255, null=True)),
                ('TIPO_ARMADO', models.CharField(blank=True, max_length=255, null=True)),
                ('PROPIETARIO', models.CharField(blank=True, max_length=255, null=True)),
                ('ANGULO', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('OBSERVACION', models.TextField(blank=True, null=True)),
                ('COMPARTE', models.CharField(blank=True, max_length=255, null=True)),
                ('CODIGO_ARMA', models.CharField(blank=True, max_length=255, null=True)),
                ('TERNAS', models.CharField(blank=True, max_length=255, null=True)),
                ('DISPOSICION', models.CharField(blank=True, max_length=255, null=True)),
                ('FUNCION_ARM', models.CharField(blank=True, max_length=255, null=True)),
                ('ESFUERZO', models.CharField(blank=True, max_length=255, null=True)),
                ('ETIQUETA', models.CharField(blank=True, max_length=255, null=True)),
                ('AMT', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KMLFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='kml/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tramo_MT',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ID_SALIDA_M', models.CharField(blank=True, max_length=255, null=True)),
                ('TENSION_NOM', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ID_CONFIGUR', models.IntegerField(blank=True, null=True)),
                ('PROPIEDAD', models.CharField(blank=True, max_length=255, null=True)),
                ('ESTADO', models.CharField(blank=True, max_length=255, null=True)),
                ('LONGITUD', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('LATITUD1', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('LONGITUD1', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('LATITUD2', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('LONGITUD2', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('DESCRIPCION', models.TextField(blank=True, null=True)),
                ('OBSERVACION', models.TextField(blank=True, null=True)),
                ('NOMBRE_PROP', models.CharField(blank=True, max_length=255, null=True)),
                ('TIPO_CIRCUI', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subestacion',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CODIGO', models.CharField(blank=True, max_length=255, null=True)),
                ('ID_SALIDAMT', models.CharField(blank=True, max_length=255, null=True)),
                ('TENSION1', models.CharField(blank=True, max_length=255, null=True)),
                ('TENSION2', models.CharField(blank=True, max_length=255, null=True)),
                ('TENSION3', models.CharField(blank=True, max_length=255, null=True)),
                ('MAXIMA_DEMA', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('POTENCIA_IN', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('SUBCOMPONEN', models.CharField(blank=True, max_length=255, null=True)),
                ('CODIGO_VNR', models.CharField(blank=True, max_length=255, null=True)),
                ('PROPIEDAD', models.CharField(blank=True, max_length=255, null=True)),
                ('ESTADO', models.CharField(blank=True, max_length=255, null=True)),
                ('LATITUD', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('LONGITUD', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('ID_NODO', models.IntegerField(blank=True, null=True)),
                ('TIPO_CONEXI', models.CharField(blank=True, max_length=255, null=True)),
                ('TIPO_SUBEST', models.CharField(blank=True, max_length=255, null=True)),
                ('OBSERVACION', models.TextField(blank=True, null=True)),
                ('NOMBRE_PROP', models.CharField(blank=True, max_length=255, null=True)),
                ('GRUPO_CONEX', models.CharField(blank=True, max_length=255, null=True)),
                ('CANTIDAD_TR', models.IntegerField(blank=True, null=True)),
                ('UBICACION', models.CharField(blank=True, max_length=255, null=True)),
                ('TIPO_VIA', models.CharField(blank=True, max_length=255, null=True)),
                ('NOMBRE_VIA', models.CharField(blank=True, max_length=255, null=True)),
                ('MANZANA', models.CharField(blank=True, max_length=255, null=True)),
                ('LOTE', models.CharField(blank=True, max_length=255, null=True)),
                ('DISTRITO', models.CharField(blank=True, max_length=255, null=True)),
                ('PROVINCIA', models.CharField(blank=True, max_length=255, null=True)),
                ('DEPARTAMENT', models.CharField(blank=True, max_length=255, null=True)),
                ('CODIGO_UBIG', models.CharField(blank=True, max_length=255, null=True)),
                ('ALTURA', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('FACTOR_UTIL', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('OPERATIVO', models.CharField(blank=True, max_length=255, null=True)),
                ('ELECTRIFICA', models.CharField(blank=True, max_length=255, null=True)),
                ('SISTEMA_ELE', models.CharField(blank=True, max_length=255, null=True)),
                ('SECTOR_TIPI', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'unique_together': {('CODIGO', 'ID_SALIDAMT')},
            },
        ),
    ]
