# Generated by Django 4.2.6 on 2023-10-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGIS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccionador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=255)),
                ('id_vano_mt', models.IntegerField()),
                ('id_subestacion', models.IntegerField()),
                ('tension_nominal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('codigo_vnr', models.CharField(max_length=255)),
                ('tipo_instalacion', models.CharField(max_length=255)),
                ('propiedad', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('fecha_servicio', models.DateField()),
                ('fecha_retiro', models.DateField()),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('systime', models.DateTimeField()),
                ('funcion', models.CharField(max_length=255)),
                ('abierto', models.BooleanField()),
                ('tipo', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('operativo', models.BooleanField()),
                ('corriente_nominal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('nombre_propietario', models.CharField(max_length=255)),
                ('fecha_instalacion', models.DateField()),
                ('observacion', models.TextField()),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marca', models.CharField(max_length=255)),
                ('serie', models.CharField(max_length=255)),
                ('norma', models.CharField(max_length=255)),
                ('icc', models.DecimalField(decimal_places=2, max_digits=7)),
                ('bill', models.DecimalField(decimal_places=2, max_digits=7)),
                ('corriente', models.DecimalField(decimal_places=2, max_digits=7)),
                ('aislante', models.CharField(max_length=255)),
                ('maniobra', models.CharField(max_length=255)),
                ('id_nodo', models.IntegerField()),
            ],
        ),
    ]
