# Generated by Django 4.2.6 on 2023-10-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGIS', '0003_remove_seccionador_fecha_instalacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccionador',
            name='amt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
