# Generated by Django 4.2.6 on 2023-10-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGIS', '0004_seccionador_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionador',
            name='tension_nominal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
