# Generated by Django 4.2.6 on 2023-10-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGIS', '0005_alter_seccionador_tension_nominal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionador',
            name='abierto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seccionador',
            name='operativo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
