# Generated by Django 4.2.6 on 2023-10-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGIS', '0006_alter_seccionador_abierto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramo_mt',
            name='TENSION_NOM',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
