# Generated by Django 4.2.6 on 2023-10-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGIS', '0007_alter_tramo_mt_tension_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramo_mt',
            name='DESCRIPCION',
        ),
        migrations.AddField(
            model_name='tramo_mt',
            name='AMT',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
