# Generated by Django 4.2.8 on 2024-02-07 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaTension', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediatension',
            options={'ordering': ['id'], 'verbose_name': 'Diagramas', 'verbose_name_plural': 'MediaTensions'},
        ),
    ]
